scalar Any

type Query {
  scores(
    space: String = ""
    network: String!
    snapshot: Any = "latest"
    strategies: [Any]!
    addresses: [String]!
  ): Scores
}

type Scores {
  scores: [Any]
  state: String
}
