name: Test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    strategy:
      matrix:
        target: ['22']
    uses: snapshot-labs/actions/.github/workflows/test.yml@main
    with:
      target: ${{ matrix.target }}
    secrets: inherit
